Upgrade to latest version of react-native-windows
This fixes a build issue with Folly and latest MSVC version due to
missing compiler builtins.

Error message is as follows:

`folly\portability\Builtins.h(109,15): error C3861: '__builtin_ctzll': identifier not found`

Fixed upstream in https://github.com/facebook/folly/commit/7dcf1524c340e410fe95170b4a920de54d666214.

Uses the ^ prefix for the package specifier so that yarn picks
minor and patch version updates automatically on install.